[package]
name = "fffish-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
ffxivfishing = { path = "../ffxivfishing" }
chrono = "*"
crossterm = "*"
ratatui = "*"
color-eyre = "*"
tui-input = "*"
confy = "*"
serde = "1.0.219"
